'use strict';const $=id=>document.getElementById(id);let state={items:[],fixtures:[]},active=null,loading=false;const labels={queued:'В очереди',processing:'Обрабатывается',retrying:'Ожидает повторной доставки',completed:'Завершено',failed:'Ошибка очереди'};
async function api(path,method='GET',body){const r=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const value=await r.json();if(!r.ok)throw Error(value.error||'Ошибка запроса');return value}
function message(text){$('message').textContent=text}
function show(job){active=job.id;$('empty').hidden=true;$('result').hidden=false;$('title').textContent=job.job.issue.summary;$('status').textContent=labels[job.status];$('timeline').replaceChildren();for(const event of job.events){const li=document.createElement('li');const type=document.createElement('strong');type.textContent=event.type;const text=document.createElement('p');text.textContent=event.detail;const time=document.createElement('small');time.textContent=new Date(event.at).toLocaleTimeString('ru-RU',{hour12:false})+' · '+event.at;li.append(type,text,time);$('timeline').append(li)}$('replay').disabled=!['completed','failed'].includes(job.status);$('answer').hidden=!job.result;$('analysis').textContent=job.result?.finalResponse||'';$('json').textContent=JSON.stringify(job,null,2)}
function render(){const fixture=state.fixtures.find(x=>x.id===$('fixture').value);$('preview').textContent=fixture?.description||'Описание отсутствует. Агент должен запросить контекст.';$('worker').textContent=state.worker.online?'На связи':'Нет свежего heartbeat';$('connection').textContent=state.queue.ok?'NATS подключён':'NATS недоступен';$('pending').textContent=(state.queue.consumers?.worker.numPending??'—')+' / '+(state.queue.consumers?.worker.numAckPending??'—');$('measured').textContent='Источник: NATS consumer info + heartbeat worker. Измерено: '+state.at;$('history').replaceChildren();for(const item of state.items){const button=document.createElement('button');button.textContent=item.job.issue.summary;const status=document.createElement('small');status.textContent=labels[item.status];button.append(status);button.onclick=()=>show(item);$('history').append(button)}if(!state.items.length)$('history').textContent='Заданий пока нет.';const current=state.items.find(x=>x.id===active);if(current)show(current)}
async function refresh(){if(loading)return;loading=true;try{state=await api('state');render()}catch(error){message(error.message)}finally{loading=false}}
$('fixture').onchange=render;$('submit').onclick=async()=>{$('submit').disabled=true;try{const job=await api('jobs','POST',{fixture:$('fixture').value,redelivery:$('redelivery').checked});active=job.id;show(job);message('JetStream принял задание. Наблюдаем доставку.');await refresh()}catch(error){message(error.message)}finally{$('submit').disabled=false}};
$('replay').onclick=async()=>{try{await api('jobs/'+active+'/replay','POST');message('Повтор отправлен в настоящую очередь. Следите за duplicate_ignored.');await refresh()}catch(error){message(error.message)}};
$('reset').onclick=async()=>{try{await api('jobs','DELETE');active=null;$('result').hidden=true;$('empty').hidden=false;message('Ваша история удалена. Очередь пропустит оставшиеся сообщения удалённых заданий.');await refresh()}catch(error){message(error.message)}};
refresh();setInterval(()=>{if(!document.hidden)refresh()},1500);
