import { createServer } from 'node:http';
import { createHash,createHmac,randomBytes,timingSafeEqual } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { connectNats,encodeJson } from './common.js';
import { openJetStream,jetStreamReadiness,YT_CODEX_STREAM,GATEWAY_RESULTS_DURABLE,YT_CODEX_JOB_SUBJECT } from './jetstream.js';
import {db,FIXTURES,cleanup,owned,row,serialize,event,create} from './portfolio-store.js';

const secret=process.env.PORTFOLIO_SECRET||'';if(secret.length<32)throw Error('A signing secret is required');
const nc=await connectNats('portfolio-demo-gateway');const{js}=await openJetStream(nc);const web=fileURLToPath(new URL('../portfolio/web/',import.meta.url));
const results=await(await js.consumers.get(YT_CODEX_STREAM,GATEWAY_RESULTS_DURABLE)).consume({max_messages:1});
(async()=>{for await(const msg of results){try{const result=msg.json(),stored=row(result.jobId);if(stored&&stored.status!=='completed'){db.prepare("UPDATE jobs SET status='completed',result=? WHERE id=?").run(JSON.stringify(result),result.jobId);event(result.jobId,'result_applied','Gateway применил результат один раз; комментарий YouTrack остаётся моковым');}msg.ack()}catch(error){console.error('Result consumer:',error.message);msg.nak(3000)}}})().catch(error=>{console.error(error);process.exit(1)});
setInterval(cleanup,300000).unref();
function session(req,res){let token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('portfolio_agents='))?.slice(17)||'';const parts=token.split('.');let valid=false;if(parts.length===3&&parts[0].length===48&&/^\d+$/.test(parts[1])&&Number(parts[1])>Date.now()){const expected=createHmac('sha256',secret).update(parts.slice(0,2).join('.')).digest('hex');valid=expected.length===parts[2].length&&timingSafeEqual(Buffer.from(expected),Buffer.from(parts[2]))}if(!valid){const raw=randomBytes(24).toString('hex')+'.'+(Date.now()+3600000);token=raw+'.'+createHmac('sha256',secret).update(raw).digest('hex');res.setHeader('Set-Cookie','portfolio_agents='+token+'; Max-Age=3600; Path=/; Secure; HttpOnly; SameSite=Lax')}return createHash('sha256').update(token).digest('hex')}
function send(res,status,value){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value))}
async function body(req){let data='';for await(const chunk of req){data+=chunk;if(Buffer.byteLength(data)>2048)throw Object.assign(Error('Слишком большой запрос'),{status:413})}try{return JSON.parse(data||'{}')}catch{throw Object.assign(Error('Некорректный JSON'),{status:400})}}
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local');if(req.method==='GET'&&url.pathname==='/healthz'){const ready=await jetStreamReadiness(nc);return send(res,ready.ok?200:503,{status:ready.ok?'ready':'unavailable'})}if(req.method==='GET'&&['/','/assets/style.css','/assets/app.js'].includes(url.pathname)){const file=url.pathname==='/'?'index.html':url.pathname.split('/').pop();res.writeHead(200,{'Content-Type':file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':'text/html; charset=utf-8'});return res.end(await readFile(web+file))}if(!url.pathname.startsWith('/api/'))return send(res,404,{error:'Не найдено'});const owner=session(req,res);cleanup();
 if(req.method==='GET'&&url.pathname==='/api/state'){const ready=await jetStreamReadiness(nc),heartbeat=db.prepare("SELECT at FROM heartbeat WHERE name='worker'").get();return send(res,200,{fixtures:FIXTURES,items:db.prepare('SELECT * FROM jobs WHERE owner=? ORDER BY created DESC').all(owner).map(serialize),queue:ready,worker:{online:!!heartbeat&&Date.now()-heartbeat.at<10000,at:heartbeat?new Date(heartbeat.at).toISOString():null},at:new Date().toISOString()})}
 if(req.method==='POST'&&url.pathname==='/api/jobs'){const input=await body(req),fixture=FIXTURES.find(x=>x.id===input.fixture);if(!fixture||Object.keys(input).some(x=>!['fixture','redelivery'].includes(x))||(input.redelivery!==undefined&&typeof input.redelivery!=='boolean'))return send(res,422,{error:'Разрешены только встроенные примеры и флаг повтора'});const job=create(owner,fixture,!!input.redelivery);try{await js.publish(YT_CODEX_JOB_SUBJECT,encodeJson(job),{msgID:job.id});event(job.id,'queued','NATS подтвердил запись в JetStream')}catch(error){db.prepare("UPDATE jobs SET status='failed' WHERE id=?").run(job.id);event(job.id,'queue_error','Очередь временно недоступна');throw error}return send(res,201,serialize(row(job.id)))}
 const match=url.pathname.match(/^\/api\/jobs\/([a-f0-9-]+)(\/replay)?$/);if(match){const job=owned(match[1],owner);if(!job)return send(res,404,{error:'Задание не найдено в вашей сессии'});if(req.method==='GET'&&!match[2])return send(res,200,serialize(job));if(req.method==='POST'&&match[2]){if(JSON.parse(job.events).filter(x=>x.type==='replay_requested').length>=3)return send(res,429,{error:'Не более трёх повторов одного задания'});if(!['completed','failed'].includes(job.status))return send(res,409,{error:'Дождитесь завершения текущей доставки'});await js.publish(YT_CODEX_JOB_SUBJECT,encodeJson(JSON.parse(job.payload)));event(job.id,'replay_requested','То же задание повторно отправлено в очередь');return send(res,200,{queued:true,id:job.id})}}
 if(req.method==='DELETE'&&url.pathname==='/api/jobs'){db.prepare('DELETE FROM jobs WHERE owner=?').run(owner);return send(res,200,{reset:true})}send(res,404,{error:'Не найдено'});
 }catch(error){console.error('Demo request:',error.message);if(!res.headersSent)send(res,error.status||503,{error:error.status?error.message:'Сервис временно не готов. Повторите позже.'});else res.end()}});
server.listen(8000,'0.0.0.0');
